#!/usr/bin/env python
# send sysrq key to virtual guest os
# usage: vbox-sysrq vmname key
# example: vbox-sysrq myvm01 t ###will send sysrq-m to guest, trigger a trace show
import sys
import commands

def usage():
    print "usage: %s vmname key" % (sys.argv[0])
    sys.exit(1)

#keycode maps
KEY_MAP = {
            "c": "2e", "m": "32", "t": "14", "p" : "19", \
            "e": "12", "f": "21", "i": "17", "j" : "24", \
            "l": "26", "n": "31", "q": "10", "w" : "11", \
            "z": "2c"
          }


VBOX_CMD = "vboxmanage controlvm %s keyboardputscancode 1D 38 54 %s %s \
            D4 B8 9D"

def main():
    try:
       key_press = KEY_MAP[sys.argv[2].lower()]
       key_up = "%x" % (int(key_press, 16) + 0x80)
       vbox_cmd = VBOX_CMD % (sys.argv[1], key_press, key_up)
    except Exception, e:
       usage()
    commands.getoutput(vbox_cmd) 
         
main() 

   
